[2025-04-10T13:38:33.874+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-10T13:38:33.919+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: beer_data_processing.create_fact_table manual__2025-04-10T13:36:07.917582+00:00 [queued]>
[2025-04-10T13:38:33.941+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: beer_data_processing.create_fact_table manual__2025-04-10T13:36:07.917582+00:00 [queued]>
[2025-04-10T13:38:33.943+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 6
[2025-04-10T13:38:33.972+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_fact_table> on 2025-04-10 13:36:07.917582+00:00
[2025-04-10T13:38:34.003+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'beer_data_processing', 'create_fact_table', 'manual__2025-04-10T13:36:07.917582+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/beer_data_processing_dag.py', '--cfg-path', '/tmp/tmp87pv5s4t']
[2025-04-10T13:38:34.012+0000] {standard_task_runner.py:105} INFO - Job 291: Subtask create_fact_table
[2025-04-10T13:38:34.013+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10878) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-10T13:38:34.016+0000] {standard_task_runner.py:72} INFO - Started process 10911 to run task
[2025-04-10T13:38:34.202+0000] {task_command.py:467} INFO - Running <TaskInstance: beer_data_processing.create_fact_table manual__2025-04-10T13:36:07.917582+00:00 [running]> on host 3e53738720c8
[2025-04-10T13:38:34.433+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='beer_data_processing' AIRFLOW_CTX_TASK_ID='create_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T13:36:07.917582+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-10T13:36:07.917582+00:00'
[2025-04-10T13:38:34.439+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-10T13:38:34.440+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-10T13:38:34.442+0000] {logging_mixin.py:190} INFO - Current task name:create_fact_table state:running start_date:2025-04-10 13:38:33.920304+00:00
[2025-04-10T13:38:34.443+0000] {logging_mixin.py:190} INFO - Dag name:beer_data_processing and current dag run status:running
[2025-04-10T13:38:34.444+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-10T13:38:34.617+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/beer_data_processing_dag.py", line 147, in populate_fact_table
    with open(beer_mapping_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2025-04-10T13:38:34.668+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-10T13:38:34.670+0000] {logging_mixin.py:190} INFO - Task start:2025-04-10 13:38:33.920304+00:00 end:2025-04-10 13:38:34.667500+00:00 duration:0.747196
[2025-04-10T13:38:34.672+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): create_fact_table> dag:<DAG: beer_data_processing> dagrun:<DagRun beer_data_processing @ 2025-04-10 13:36:07.917582+00:00: manual__2025-04-10T13:36:07.917582+00:00, state:running, queued_at: 2025-04-10 13:36:08.187437+00:00. externally triggered: True>
[2025-04-10T13:38:34.673+0000] {logging_mixin.py:190} INFO - Failure caused by expected str, bytes or os.PathLike object, not NoneType
[2025-04-10T13:38:34.675+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=beer_data_processing, task_id=create_fact_table, run_id=manual__2025-04-10T13:36:07.917582+00:00, execution_date=20250410T133607, start_date=20250410T133833, end_date=20250410T133834
[2025-04-10T13:38:34.747+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-10T13:38:34.749+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 291 for task create_fact_table (expected str, bytes or os.PathLike object, not NoneType; 10911)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/beer_data_processing_dag.py", line 147, in populate_fact_table
    with open(beer_mapping_path, 'r') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2025-04-10T13:38:34.801+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-10T13:38:34.860+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-10T13:38:34.864+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
